---
# tasks file for helm

- name: Install Helm dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
    state: present

- name: Add Helm GPG apt Key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Helm Repository
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Update apt and install helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
