---
# tasks file for docker

- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: present

- name: Install docker dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: present

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Prevent docker-ce from being upgraded
  ansible.builtin.dpkg_selections:
    name: docker-ce
    selection: hold

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Add admin user to docker group
  ansible.builtin.user:
    name: admin
    groups: docker
    append: true

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: true
