---
- name: CheckMK Server
  hosts: checkmk-server
  vars_files: /code/vault/ash.yml
  become: true
  roles:
    - common
    - checkmk.general.server
  vars:
    checkmk_server_version: "2.2.0p17"
    checkmk_server_edition: cre
    checkmk_server_sites:
    - name: monitor
      version: "{{ checkmk_server_version }}"
      update_conflict_resolution: abort
      state: started
      admin_pw: "{{ vault_checkmk_password }}"
      omd_auto_restart: 'false'
      omd_config:
        - var: AUTOSTART
          value: on

  tasks:
    - name: Create backup directory if it does not exist
      ansible.builtin.file:
        path: /mnt/backup
        state: directory

    - name: Mount an NFS backup volume
      ansible.posix.mount:
        src: 192.168.12.5:/mnt/Warm/Backup
        path: /mnt/backup
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
