---
- name: Bind DNS
  hosts: dns
  vars_files: /code/vault/ash.yml
  become: true
  roles:
    - common
    - dns
    - checkmk.general.agent
  vars:
    checkmk_agent_version: "2.2.0p17"
    checkmk_agent_edition: "cre"
    checkmk_agent_user: "cmkadmin"
    checkmk_agent_pass: "{{ vault_checkmk_password }}"
    # Here comes the part, where we get into remote registration
    checkmk_agent_server_protocol: http
    # The following should be set to the central site.
    # This where you configure the host objects.
    # Currently the agent package is also pulled from here.
    checkmk_agent_server: checkmk.dataknife.net
    checkmk_agent_site: "monitor"
    # The following should be pointed to the respective remote site.
    # This is where the registration will happen.
    checkmk_agent_registration_server: "{{ checkmk_agent_server }}"
    checkmk_agent_registration_site: monitor
    # These options need to be enabled for all registrations to work.
    # You can however disable the one you do not want to perform.
    # But the host needs to be added and changes activated in any case.
    checkmk_agent_auto_activate: 'true'
    checkmk_agent_update: 'true'
    checkmk_agent_tls: 'false'
    checkmk_agent_add_host: 'true'
    # These are some generic agent options you might want to configure.
    checkmk_agent_discover: 'true'
    checkmk_agent_discover_max_parallel_tasks: 0
    checkmk_agent_force_install: 'true'
    checkmk_agent_delegate_api_calls: localhost
    checkmk_agent_delegate_download: "{{ inventory_hostname }}"
    checkmk_agent_host_name: "{{ inventory_hostname }}"
    checkmk_agent_host_folder: "{{ checkmk_var_site }}"
    checkmk_agent_host_ip: "{{ ansible_host }}"
    checkmk_agent_host_attributes:
      ipaddress: "{{ checkmk_agent_host_ip | default(omit) }}"
